easy_admin:
    site_name: '<img src="/images/logo.png" />'
    formats:
        date:     'Y-m-d'
        time:     'H:i'
        datetime: 'Y-m-d H:i:s'
    entities:
        # List the entity class name you want to manage
        Article:
            class: App\Entity\Article
            list:
                fields:
                    - { property: 'id', label: '#' }
                    - { property: 'title', label: 'Titre' }
                    - { property: 'subtitle', label: 'Sous-titre' }
                    - { property: 'image', label: 'Illustration', type: 'image' }
                    - { property: 'creationDate', label: 'Créé le' }
            form:
                fields:
                    - title
                    - subtitle
                    - content
                    - image
                    - tags
            search:
                fields: ['title', 'subtitle', 'content']
