easy_admin:
    site_name: '<img src="/images/logo.png" />'
    formats:
        date:     'Y-m-d'
        time:     'H:i'
        datetime: 'Y-m-d H:i:s'
    entities:
        # List the entity class name you want to manage
        Article:
            class: App\Entity\Article
            list:
                fields:
                    - { property: 'id', label: '#' }
                    - { property: 'published', label: 'Publié ?' }
                    - { property: 'title', label: 'Titre' }
                    - { property: 'subtitle', label: 'Sous-titre' }
                    - { property: 'image', label: 'Illustration', type: 'image', base_path: '/uploads/files' }
                    - { property: 'creationDate', label: 'Créé le' }
            form:
                fields:
                    - title
                    - subtitle
                    - tags
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'content', type: 'code_editor', language: 'markdown' }
            search:
                fields: ['title', 'subtitle', 'content']
