easy_admin:
    site_name: '<img src="/images/logo.png" />'
    formats:
        date:     'Y-m-d'
        time:     'H:i'
        datetime: 'Y-m-d H:i:s'
    entities:
        # List the entity class name you want to manage
        Article:
            class: App\Entity\Article
            list:
                actions:
                    - { name: 'app_customadmin_front', type: 'route', icon: 'external-link', label: '' }
                fields:
                    - { property: 'id', label: '#' }
                    - { property: 'published', label: 'Publié ?' }
                    - { property: 'author', label: 'Auteur' }
                    - { property: 'title', label: 'Titre' }
                    - { property: 'slug', label: 'Slug' }
                    - { property: 'image', label: 'Illustration', type: 'image', base_path: '/uploads/files' }
                    - { property: 'creationDate', label: 'Créé le' }
            form:
                fields:
                    - { property: 'author', label: 'Auteur' }
                    - { property: 'title', label: 'Titre' }
                    - { property: 'slug', label: 'Slug', type_options: { disabled: true } }
                    - { property: 'subtitle', label: 'Sous-titre' }
                    - tags
                    - { property: 'imageFile', label: 'Illustration', type: 'vich_image' }
                    - { property: 'content', label: 'Contenu', type: 'text_editor', language: 'markdown' }
            search:
                fields: ['title', 'subtitle', 'content']
